### ISSUE TITLE
Error report of original unit test execution

### ISSUE THREAD

**Issue by 601724080** [SurpSG/jacoco-gradle-plugin-merge-coverage#1] opened 2020-02-10 02:34 UTC
I download the code to the local and execute “. / gradlew clean jacocorootreport” has no problem, but there is an error when executing class1test.printmax in idea. The error is as follows:

Testing started at 10:23 ...
> Task :code-and-tests:cleanTest UP-TO-DATE
> Task :code-only:compileJava FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':code-only:compileJava'.
> Could not resolve all files for configuration ':code-only:compileClasspath'.
   > Could not resolve org.jacoco:org.jacoco.agent:0.8.2.
     Required by:
         project :code-only
      > No cached version of org.jacoco:org.jacoco.agent:0.8.2 available for offline mode.
      > No cached version of org.jacoco:org.jacoco.agent:0.8.2 available for offline mode.
      > No cached version of org.jacoco:org.jacoco.agent:0.8.2 available for offline mode.
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Get more help at https://help.gradle.org
BUILD FAILED in 1s
2 actionable tasks: 1 executed, 1 up-to-date

So I added "org. Jacoco: org. Jacoco. Agent: 0.8.2" dependency in the subproject, but it didn't work

**Comment by SurpSG** [comment] 2020-02-10 18:06
Hi, @601724080 
Unfortunately, cannot reproduce on my machine 
Seems, there is the same issue https://stackoverflow.com/questions/37409265/no-cached-version-available-for-offline-mode
Please, follow the link above

**Comment by 601724080** [comment] 2020-02-11 01:46
OK, that should be the error of my environment. Thank you for providing this demo

**Comment by SurpSG** [comment] 2020-02-11 10:51
Welcome!
May I close the issue?

**Comment by 601724080** [comment] 2020-02-11 11:01
Certainly. I'm sorry, but it's my idea that turns off the offline module. When I turn on the offline module, everything is OK

**Comment by SurpSG** [comment] 2020-02-11 14:15
Happy that it works for you

**Closed as completed by SurpSG** 2020-02-11 14:15 UTC
